resources:
  - name: myHelm
    type: HelmChart
    configuration: 
      sourceArtifactory: myArtifactoryIntegration
      repository: helm
      chart: aerospike
      version: 0.1.5
      
      
pipelines:
  - name: pipelines_auto11
    steps:
      - name: new_pipelines11
        type: Bash
        configuration: 
          inputResources:
            - name: myHelm
        execution:
          onExecute:
            - echo "hi"      
      
      
