resources:
  - name: myHelm
    type: HelmChart
    configuration: 
      sourceArtifactory: s_artifactory
      repository: helm-remote
      chart: bindu
      version: 0.0.1
      
      
pipelines:
  - name: pipelines_auto11
    steps:
      - name: new_pipelines11
        type: Bash
        configuration: 
          inputResources:
            - name: myHelm
        execution:
          onExecute:
            - echo "hi"      
