resources:
  - name: my_repo
    type: GitRepo
    configuration:
      path: bindushree16/test1
      branches:
        include: ^master$
      gitProvider: bindu_github
      


pipelines:
  - name: Pipeline
    steps:
      - name: FanOut_Matrix_1
        type: FanOut    
        execution: 
          onExecute:
            - echo "I am on fan out step"
            - touch fan_out.txt
            - set_step_var fan_out value1
            - echo "Fan out working" > fan_out_1.txt

#       - name: FanOut_Matrix_2
#         type: FanOut
#         configuration:
#           inputSteps: 
#             - name: FanOut_Matrix_1      
#         execution: 
#           onExecute:
#             - echo "I am on fan out step"
    
    
    
#       - name: my_Step_1
#         type: Matrix
#         stepMode: Bash
#         configuration:
#           inputResources:
#             - name: my_repo
#         stepletMultipliers:
#           environmentVariables:
#             - env1: onee
#         execution:
#           onExecute:
#             - echo "hi"   
            
      - name: my_Step
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps: 
#             - name: FanOut_Matrix_2
            - name: FanOut_Matrix_1
        stepletMultipliers:
          environmentVariables:
            - env1: one
              env2: two
              env3: three
            - env1: changed1
              env2: changed2
            - key_1: value1
              key_2: value2
          runtimes:
            - type: image
              image:
                auto:
                  language: java
                  versions:
                    - 13.0
            - type: image
              image:
                auto:
                  language: node
                  versions:
                    - 8.17.0
        execution:
          onExecute:
            - echo "hi"       
            - ls -l ./FanOut_Matrix_1
            - touch ${steplet_id}_file
            - echo "Created file on steplet ${steplet_id}" > ${steplet_id}_file
            - echo "Envs env1 = $env1 , env2 = $env2 , env3 = $env3" >> ${steplet_id}_file
            - echo "Runtime image name - $step_image_name, Runtime image tag - $step_image_tag" >> ${steplet_id}_file
            - set_step_var test_key "$(date)"
            - set_step_var key "https://www.go.in/${env1}/${steplet_id}"
            - get_step_var FanOut_Matrix_1 fan_out
            - pushd "$res_my_repo_resourcePath/"
            
           
            
            
      - name: martix_FanInnnn
        type: FanIn
        configuration:
          inputSteps: 
#             - name: FanOut_Matrix_2
            - name: my_Step
        execution:
          onExecute:
            - echo "Hello"
            - echo "I am on fan out step"
            - ls -l .
            - ls -l ./my_Step
            - ls -l ./my_Step/FanOut_Matrix_1/
            - get_step_var my_Step test_key
            - get_step_var my_Step addresses
#       - name: Matrix_Fan
#         type: FanIn
#         configuration:
#           inputSteps: 
#             - name: Matrix_Fan_In_step
#         execution:
#           onExecute:
#             - echo "Hello"
#       - name: Matrix_Fan22
#         type: FanIn
#         configuration:
#           inputSteps: 
#             - name: Matrix_Fan
#         execution:
#           onExecute:
#             - echo "Hello" 

 
