  
resources:
  - name: repooo_bindu
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/automation_for_gcp 
      buildOn:
         commit: false 
         
  - name: my_releaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: bindu_dist
      name: my_release_bundle
      version: v0.2.21
 #     isSigned:  # optional     
 
pipelines:
  - name: pipeline11
    steps:
      - name: node
        type: Bash
        configuration:
          outputResources:
            - name: my_releaseBundle
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - printenv
            - res_my_releaseBundle_version=v4.0.0
    
      - name: nava
        type: Bash
        configuration:
          inputResources:
            - name: my_releaseBundle
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - printenv       

