resources:
  - name: S_Bash_0085_BuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: i_artifactory
      buildName: mvn_sample_build_auto
      buildNumber: 1
      
          
pipelines:
  - name: pipelines_auto
    steps:
      - name: S_Bash_0085
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0085_BuildInfo
              trigger: true
        execution:
          onExecute:
            - printenv 
