# resources:
#   - name: GitRepo
#     type: GitRepo
#     configuration:
#       path: bindushree16/test1
#       gitProvider: bi

##node
# pipelines:
#   - name: pipelines_auto
#     steps:
#       - name: new_pipeline1
#         type: Bash
#         configuration:
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: node 
#                 versions:
#                   - 10.18.0
#         execution:
#           onExecute:
#             - printenv

#       - name: new_pipeline2
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: new_pipeline1
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: node 
#                 versions:
#                   - "8.17.0"
#         execution:
#           onExecute:
#             - printenv
            
#       - name: new_pipeliness
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: new_pipeline2
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: node 
#                 versions:
#                   - "12.14.0"
#         execution:
#           onExecute:
#             - printenv      

# #ccp
# pipelines:
#   - name: pipelines_auto
#     steps:
#       - name: new_pipeline3
#         type: Bash
#         configuration:
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: cpp
#                 versions:
#                   - 9.0.0
#         execution:
#           onExecute:
#             - printenv
            
#       - name: new_pipeline4
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: new_pipeline3
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: cpp
#                 versions:
#                   - "8.0.0"
#         execution:
#           onExecute:
#             - printenv  

# #java
pipelines:
  - name: pipelines_auto
    steps:
      - name: new_pipeline5
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "8"
        execution:
          onExecute:
            - printenv

      - name: new_pipeline6
        type: Bash
        configuration:
          inputSteps:
            - name: new_pipeline5
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 11
        execution:
          onExecute:
            - printenv  
            
      - name: new_pipeline7
        type: Bash
        configuration:
          inputSteps:
            - name: new_pipeline6
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "13"
        execution:
          onExecute:
            - printenv  

##go 
# pipelines:
#   - name: pipelines_auto
#     steps:
#       - name: new_pipeline8
#         type: Bash
#         configuration:
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: go
#                 versions:
#                   - 1.11.13
#         execution:
#           onExecute:
#             - printenv

#       - name: new_pipeline9
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: new_pipeline8
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: go
#                 versions:
#                   - "1.12.14"
#         execution:
#           onExecute:
#             - printenv 

#       - name: new_pipeline10
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: new_pipeline9
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: go
#                 versions:
#                   - "1.13.5"
#         execution:
#           onExecute:
#             - printenv 
            
            
            
            
            
            
          


# resources:
#   - name: S_Bash_0085_BuildInfo
#     type: BuildInfo
#     configuration:
#       sourceArtifactory: i_artifactory
#       buildName: mvn_sample_build_auto
#       buildNumber: 1
      
          
# pipelines:
#   - name: pipelines_auto
#     steps:
#       - name: S_Bash_0085
#         type: Bash
#         configuration:
#           inputResources:
#             - name: S_Bash_0085_BuildInfo
#               trigger: true
#         execution:
#           onExecute:
#             - printenv 
